on:
  push:
  issues:
    types: [opened, deleted, closed, reopened, labeled, unlabeled, milestoned, demilestoned]
  issue_comment:
    types: [created, edited, deleted]
  milestone:
    types: [created, edited, deleted]
name: Process changes and deploy

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0 

    - name: Cancel previous builds
      uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Process scope issue comments
      uses: ./.github/actions/process-scopes-comments
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        repo_owner: asyncapi
        repo_name: shape-up-process
    
    - name: Update progress.json
      # if: |
      #   github.event_name === 'issue_comment.created' ||
      #   github.event_name === 'issue_comment.edited' ||
      #   github.event_name === 'issue_comment.deleted'
      run: |
        core.setCommandEcho(true)
        console.log(github.event_name)
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update progress.json" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master