name: Process changes and deploy
on:
  push:
  issues:
    types: [opened, deleted, closed, reopened, labeled, unlabeled, milestoned, demilestoned]
  issue_comment:
    types: [created, edited, deleted]
  milestone:
    types: [created, edited, deleted]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0 

    - name: Process scope issue comments
      uses: ./.github/actions/process-scopes-comments
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        repo_owner: asyncapi
        repo_name: shape-up-process
    
    - name: Update progress.json
      if: github.event_name == 'issue_comment'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --local pull.rebase false
        git commit -m "Update progress.json" -a || true
        git pull --no-edit || true
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
    
    - name: Deploy to Netlify
      if: github.event_name == 'issues' || github.event_name == 'milestone'
      uses: jsmrcaga/action-netlify-deploy@v1.1.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_TO_PROD: true
